### ISSUE TITLE
Unable to Install QT Wallet at MacOS High Sierra 10.13.14

### ISSUE THREAD

**Issue by pentonwong** [trvc/trivecoincore#1]
When trying to install the QT wallet, it keeps showing us the following message.

![screen-shot-2018-04-23-at-3 39 47-am](https://user-images.githubusercontent.com/28583461/39099191-dca34c64-46a8-11e8-9f1d-da4a4fdb88e8.png)

Please advise. Thanks!

Note: zeromq had been installed earlier.

**Comment by chooikw** [comment]
The error message shows it is missing boost library. Have you tried installing libboost?

sudo brew install boost
or
sudo port install boost
