### ISSUE TITLE
Error when install in ubuntu

### ISSUE THREAD

**Issue by yongtatsum** [trvc/trivecoincore#2]
Hi I face this error when run make

make[3]: Entering directory `/var/www/trivechain-master/src/secp256k1'
I. -Wall -Wextra -Wno-unused-function -c src/gen_context.c -o gen_context.o
/bin/bash: I.: command not found
make[3]: [gen_context.o] Error 127 (ignored)
gen_context.o -o gen_context
/bin/bash: gen_context.o: command not found
make[3]: *** [gen_context] Error 127
make[3]: Leaving directory `/var/www/trivechain-master/src/secp256k1'
make[2]: *** [secp256k1/libsecp256k1.la] Error 2
make[2]: Leaving directory `/var/www/trivechain-master/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/var/www/trivechain-master/src'
make: *** [all-recursive] Error 1

**Comment by chooikw** [comment]
Please run following command and proceed with normal compilation:
export CC_FOR_BUILD=gcc

This will set the environment variable to inform the "make" which compiler to use.
